<?php

/**
 * @file
 * Fixes a known issue where redirect loops are created when you have pathauto,
 * workbench moderation and redirect installed together.
 *
 * @see https://www.drupal.org/node/1945558#comment-7500630
 */

/**
 * Implements hook_redirect_presave().
 */
function redirect_fix_redirect_presave($redirect) {
  // Remove redirects pointing to aliases of the node it handles.
  $query = db_select('url_alias', 'u')
    ->fields('u', array('alias'));
  $query->join('redirect', 'r', 'u.alias = r.source');
  $query->fields('r', array('rid'));
  $results = $query->execute();

  foreach ($results as $record) {
    db_delete('redirect')
    ->condition('rid', $record->rid)
    ->execute();
  }
}

/**
 * Implements hook_redirect_insert().
 */
function redirect_fix_redirect_insert($redirect) {
  redirect_fix_redirect_presave($redirect);
}

/**
 * Implements hook_redirect_update().
 */
function redirect_fix_redirect_update($redirect) {
  redirect_fix_redirect_presave($redirect);
}