<?php

/**
 * @file
 * Drupal hooks.
 */

/* Add custom view modes */
/**
 * Implements hook_entity_info_alter().
 * The first attribute in the array defines an arbitrary label for the view mode machine name.
 * 'custom settings' => TRUE displays the view mode as a default at the top of the display modes settings screen
 */

function rbkc_view_modes_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['top_three_topics'] = array(
    'label' => t('View top three topics'),
    'custom settings' => TRUE,
  );
  $entity_info['node']['view modes']['carousel'] = array(
    'label' => t('Carousel'),
    'custom settings' => TRUE,
  );
  $entity_info['field_collection_item']['view modes']['teaser'] = array(
    'label' => t('Teaser'),
    'custom settings' => TRUE,
  );
  $entity_info['field_collection_item']['view modes']['top_three_topics'] = array(
    'label' => t('View top three topics'),
    'custom settings' => TRUE,
  );
  $entity_info['field_collection_item']['view modes']['carousel'] = array(
    'label' => t('Carousel'),
    'custom settings' => TRUE,
  );
}
