<?php
/**
 * @file
 * Layout definition for Planer three region layout.
 */

/**
 * Panel layout definition.
 */
$plugin = array(
  'title'    => t('Planer Three Region'),
  'category' => t('Planer'),
  'icon'     => 'planer_three_region.png',
  'theme'    => 'planer_three_region',
  'regions'  => array(
    'first'         => t('First'),
    'second'         => t('Second'),
    'third'         => t('Third'),
  ),
);
