<?php
/**
 * Implements hook_form_FORM_ID_alter().
 */
function rbkc_fe_form_node_form_alter(&$form, &$form_state) {
  // Attach javascript to the node edit form to override default scald theming.
  // It needs to happen at this point in time as the wrapping divs get inserted
  // into the textarea at the time of edit rather than at the time of rendering.
  $form['#attached']['js'][] = drupal_get_path('module', 'rbkc_fe') . '/js/scald.js';
}

/**
 * Implements hook_block_view_MODULE_DELTA_alter().
 */
function rbkc_fe_block_view_google_appliance_ga_related_searches_alter(&$data, $block) {
  if (isset($data['content']) && !empty($data['content'])) {
    $data['content'] = '<div class="related-search-terms"><p>' . t('Related search phrases:') . '</p>' . $data['content'] . '</div>';
  }
}